import { Router } from 'express';
import prismaShared from '../lib/prisma.js';
import PDFDocument from 'pdfkit';

const router = Router();
const prisma = prismaShared;

// Test route
router.get('/test', (req, res) => res.json({ status: 'ok' }));

async function verifyToken(req) {
  const token = req.query.token || req.headers.token || (req.headers.authorization ? req.headers.authorization.split(' ')[1] : null);
  if (!token) return null;
  try {
    const session = await prisma.session.findUnique({ where: { token: String(token) }, include: { user: true } });
    if (!session || (session.expiresAt && session.expiresAt < new Date())) return null;
    return session.user;
  } catch (e) { return null; }
}

const formatCurrency = (amount) => {
  return '\u20B9' + parseFloat(amount || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 });
};

const formatDate = (date) => date ? new Date(date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '-';

async function generatePremiumPDF(res, docData, business, party, title) {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'inline');
  doc.pipe(res);

  // --- HEADER SECTION ---
  doc.rect(0, 0, 600, 100).fill(business?.settings?.themeColor || '#0284c7');
  doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text(business?.name?.toUpperCase() || 'ARTHA', 40, 40);
  doc.fontSize(10).font('Helvetica').text(business?.email || '', 40, 70);
  
  doc.fillColor('#ffffff').fontSize(20).text(title.toUpperCase(), 400, 40, { align: 'right' });
  doc.fontSize(10).text(`Number: ${docData.invoiceNumber || docData.estimateNumber || docData.purchaseNumber || 'N/A'}`, 400, 70, { align: 'right' });

  // --- INFO SECTION ---
  doc.fillColor('#1e293b').fontSize(10).font('Helvetica-Bold').text('BILL FROM:', 40, 120);
  doc.font('Helvetica').text(business?.name, 40, 135);
  doc.text(business?.address?.street || '', 40, 150);
  doc.text(`${business?.address?.city}, ${business?.address?.state}`, 40, 165);

  doc.font('Helvetica-Bold').text('BILL TO:', 300, 120);
  doc.font('Helvetica').text(party?.name || 'Cash Customer', 300, 135);
  doc.text(party?.address?.street || party?.phone || '', 300, 150);
  doc.text(`Date: ${formatDate(docData.date)}`, 300, 165);

  // --- TABLE HEADER ---
  doc.rect(40, 200, 520, 25).fill('#f1f5f9');
  doc.fillColor('#475569').font('Helvetica-Bold').fontSize(9);
  doc.text('DESCRIPTION', 50, 210);
  doc.text('QTY', 350, 210, { width: 40, align: 'center' });
  doc.text('RATE', 400, 210, { width: 60, align: 'right' });
  doc.text('TOTAL', 480, 210, { width: 70, align: 'right' });

  // --- ITEMS ---
  let y = 235;
  doc.font('Helvetica').fillColor('#1e293b').fontSize(9);
  
  docData.items.forEach((it, i) => {
    if (i % 2 === 1) doc.rect(40, y - 5, 520, 25).fill('#f8fafc');
    doc.fillColor('#1e293b').text(it.item?.name || it.description || 'Service', 50, y);
    doc.text(String(it.quantity), 350, y, { width: 40, align: 'center' });
    doc.text(formatCurrency(it.rate), 400, y, { width: 60, align: 'right' });
    doc.text(formatCurrency(it.amount), 480, y, { width: 70, align: 'right' });
    y += 25;
  });

  // --- FOOTER / TOTALS ---
  doc.rect(350, y + 20, 210, 80).fill('#f8fafc');
  doc.fillColor('#475569').text('Subtotal:', 360, y + 35);
  doc.fillColor('#1e293b').text(formatCurrency(docData.subtotal || docData.totalAmount), 480, y + 35, { align: 'right', width: 70 });
  
  doc.fillColor('#475569').text('Tax Amount:', 360, y + 55);
  doc.fillColor('#1e293b').text(formatCurrency(docData.totalTax || docData.taxAmount || 0), 480, y + 55, { align: 'right', width: 70 });

  doc.rect(350, y + 75, 210, 25).fill(business?.settings?.themeColor || '#0284c7');
  doc.fillColor('#ffffff').font('Helvetica-Bold').text('GRAND TOTAL:', 360, y + 83);
  doc.text(formatCurrency(docData.totalAmount), 480, y + 83, { align: 'right', width: 70 });

  doc.fillColor('#94a3b8').fontSize(8).font('Helvetica').text('Generated by Artha Cloud Accounting', 0, 800, { align: 'center', width: 600 });
  
  doc.end();
}

router.get('/report/:reportType', async (req, res) => {
    const { reportType } = req.params;
    const { businessId, token, format } = req.query;
    const user = await verifyToken(req);
    if (!user) return res.status(401).send('Unauthorized');
    const business = await prisma.business.findFirst({ where: { id: businessId, userId: user.id } });
    if (!business) return res.status(403).send('Forbidden');

    if (format === 'CSV') {
        res.setHeader('Content-Type', 'text/csv');
        let csv = 'Date,Particulars,Amount\n';
        const data = await prisma.invoice.findMany({ where: { businessId } });
        data.forEach(x => csv += `${formatDate(x.date)},Sale ${x.invoiceNumber},${x.totalAmount}\n`);
        return res.status(200).send(csv);
    }
    const doc = new PDFDocument();
    res.setHeader('Content-Type', 'application/pdf');
    doc.pipe(res);
    doc.fontSize(20).text(`REPORT: ${reportType.toUpperCase()}`);
    doc.text(`Business: ${business.name}`);
    doc.end();
});

router.get('/:type/:id', async (req, res) => {
    const { type, id } = req.params;
    const user = await verifyToken(req);
    if (!user) return res.status(401).send('Unauthorized');

    let docData = null;
    let title = 'INVOICE';
    
    if (type === 'invoice') {
        docData = await prisma.invoice.findFirst({ where: { id, business: { userId: user.id } }, include: { items: { include: { item: true } }, party: true } });
        title = 'Tax Invoice';
    } else if (type === 'estimate') {
        docData = await prisma.estimate.findFirst({ where: { id, business: { userId: user.id } }, include: { items: { include: { item: true } }, party: true } });
        title = 'Quotation';
    } else if (type === 'purchase') {
        docData = await prisma.purchase.findFirst({ where: { id, business: { userId: user.id } }, include: { items: { include: { item: true } }, party: true } });
        title = 'Purchase Bill';
    }

    if (!docData) return res.status(404).send('Not found');
    const business = await prisma.business.findUnique({ where: { id: docData.businessId } });
    await generatePremiumPDF(res, docData, business, docData.party, title);
});

export default router;
